# Generated by Django 5.2.7 on 2025-11-06 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key_type', models.CharField(choices=[('server', 'Server key'), ('browser', 'Browser key')], default='server', max_length=20)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('bound_account', models.CharField(blank=True, help_text='Account or email bound to this key', max_length=255)),
                ('restrictions', models.TextField(blank=True, help_text='API restrictions (JSON format)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app_type', models.CharField(choices=[('web', 'Web application'), ('mobile', 'Mobile application'), ('desktop', 'Desktop application')], default='web', max_length=20)),
                ('client_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_secret', models.CharField(max_length=255)),
                ('redirect_uris', models.TextField(help_text='One URI per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_apps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Application',
                'verbose_name_plural': 'OAuth Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
