# Generated by Django 5.2.7 on 2025-11-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey_oauthapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('redirect_uri', models.URLField()),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of scopes')),
                ('code_challenge', models.CharField(blank=True, help_text='PKCE code challenge', max_length=255)),
                ('code_challenge_method', models.CharField(blank=True, choices=[('S256', 'S256'), ('plain', 'plain')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_codes', to='accounts.oauthapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorization_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Authorization Code',
                'verbose_name_plural': 'OAuth Authorization Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='None means never expires', null=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='accounts.oauthapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth Refresh Token',
                'verbose_name_plural': 'OAuth Refresh Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='accounts.oauthapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_access_tokens', to=settings.AUTH_USER_MODEL)),
                ('authorization_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to='accounts.oauthauthorizationcode')),
                ('refresh_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_tokens', to='accounts.oauthrefreshtoken')),
            ],
            options={
                'verbose_name': 'OAuth Access Token',
                'verbose_name_plural': 'OAuth Access Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
