# Generated by Django 5.2.7 on 2025-11-07 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_oauthauthorizationcode_oauthrefreshtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthConsentScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='The name of the application shown to users', max_length=100)),
                ('app_logo', models.URLField(blank=True, help_text='URL to the application logo (must be publicly accessible)')),
                ('support_email', models.EmailField(help_text='Support email address for users', max_length=254)),
                ('application_homepage', models.URLField(blank=True, help_text='Application homepage URL')),
                ('privacy_policy_url', models.URLField(blank=True, help_text='Privacy policy URL')),
                ('terms_of_service_url', models.URLField(blank=True, help_text='Terms of service URL')),
                ('authorized_domains', models.TextField(blank=True, help_text='Authorized domains (one per line). Users from these domains can access the app.')),
                ('developer_contact_email', models.EmailField(help_text='Developer contact email', max_length=254)),
                ('scope_descriptions', models.JSONField(blank=True, default=dict, help_text='Custom descriptions for scopes (JSON format: {"scope": "description"})')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_screen', to='accounts.oauthapp')),
            ],
            options={
                'verbose_name': 'OAuth Consent Screen',
                'verbose_name_plural': 'OAuth Consent Screens',
                'ordering': ['-updated_at'],
            },
        ),
    ]
