# Generated by Django 5.2.7 on 2025-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_oauthconsentscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthconsentscreen',
            name='app_description',
            field=models.TextField(blank=True, help_text='Application description shown to users (max 500 characters)', max_length=500),
        ),
        migrations.AddField(
            model_name='oauthconsentscreen',
            name='publishing_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('testing', 'Testing'), ('published', 'Published')], default='draft', help_text='Publishing status of the consent screen', max_length=20),
        ),
        migrations.AddField(
            model_name='oauthconsentscreen',
            name='scope_reasons',
            field=models.JSONField(blank=True, default=dict, help_text='Scope descriptions and reasons (JSON format: {"scope": {"description": "...", "reason": "..."}})'),
        ),
        migrations.AlterField(
            model_name='oauthconsentscreen',
            name='scope_descriptions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom descriptions for scopes (JSON format: {"scope": "description"}) - Legacy field'),
        ),
    ]
