# Generated by Django 5.2.7 on 2025-11-07 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_oauthconsentscreen_app_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='data_token',
            field=models.TextField(blank=True, help_text='Signed data token issued by SVA Core'),
        ),
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='subject',
            field=models.CharField(blank=True, help_text='Opaque subject identifier from SVA Core', max_length=64),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='approved_scopes',
            field=models.TextField(blank=True, help_text='Space-separated list of approved scopes'),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='data_token',
            field=models.TextField(blank=True, help_text='Signed data token issued by SVA Core'),
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='subject',
            field=models.CharField(blank=True, help_text='Opaque subject identifier from SVA Core', max_length=64),
        ),
        migrations.AddField(
            model_name='oauthrefreshtoken',
            name='subject',
            field=models.CharField(blank=True, help_text='Opaque subject identifier from SVA Core', max_length=64),
        ),
        migrations.AlterField(
            model_name='oauthaccesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_access_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oauthauthorizationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorization_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oauthrefreshtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_refresh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_uri', models.URLField()),
                ('scope', models.TextField(blank=True, help_text='Space-separated list of requested scopes')),
                ('state', models.CharField(blank=True, max_length=255)),
                ('code_challenge', models.CharField(blank=True, help_text='PKCE code challenge', max_length=255)),
                ('code_challenge_method', models.CharField(blank=True, choices=[('S256', 'S256'), ('plain', 'plain')], max_length=10)),
                ('nonce', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Opaque subject identifier from SVA Core', max_length=64)),
                ('approved_scopes', models.TextField(blank=True, help_text='Space-separated list of approved scopes')),
                ('data_token', models.TextField(blank=True, help_text='Signed data token issued by SVA Core')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_requests', to='accounts.oauthapp')),
            ],
            options={
                'verbose_name': 'OAuth Authorization Request',
                'verbose_name_plural': 'OAuth Authorization Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='oauthauthorizationcode',
            name='auth_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorization_code', to='accounts.oauthauthorizationrequest'),
        ),
    ]
