# Generated by Django 5.2.8 on 2025-11-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_oauthaccesstoken_data_token_oauthaccesstoken_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuthAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_scopes', models.TextField(help_text='Space-separated list of granted scopes')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='False if user has revoked access')),
                ('oauth_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_authorizations', to='accounts.oauthapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OAuth Authorization',
                'verbose_name_plural': 'User OAuth Authorizations',
                'ordering': ['-authorized_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_69f3f4_idx'), models.Index(fields=['oauth_app', 'is_active'], name='accounts_us_oauth_a_f210d4_idx')],
                'unique_together': {('user', 'oauth_app')},
            },
        ),
    ]
