# Generated by Django 5.2.8 on 2025-12-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_oauth_authorization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOAuthAuthorization',
        ),
    ]
